# définir l’image de base.
FROM python:3.12-slim

# définir le répertoire de travail dans le conteneur.
WORKDIR /p_meteo

# copier uniquement le fichier des dépendances dans l’image.
COPY requirements_console.txt .

# installer les dépendances Python.
RUN pip install --no-cache-dir -r requirements_console.txt

# copier l’intégralité du projet dans l’image.
COPY . .

# définir la commande exécutée par défaut lorsque le conteneur démarre.
CMD ["python", "-m", "p_meteo"]
