# définir l’image de base.
FROM python:3.12-slim

# définir le répertoire de travail dans le conteneur.
WORKDIR /p_meteo

# copier uniquement le fichier des dépendances dans l’image.
COPY requirements_streamlit.txt .

# installer les dépendances Python.
RUN pip install --no-cache-dir -r requirements_streamlit.txt

# copier l’intégralité du projet dans l’image.
COPY . .

# définir la commande exécutée par défaut lorsque le conteneur démarre.
CMD ["streamlit", "run", "p_meteo/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
